[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "asf_levies_model_app"
version = "0.1.0"
description = "Web app for testing new scenarios in the ASF domestic energy bills and levies model."
authors = [
    {name = "Your Name", email = "your.email@example.com"},
    {name = "Nesta", email = ""}  # Original authors
]
license = {text = "MIT"}
dependencies = [
    "streamlit>=1.48.1",
    "altair",
    "pandas",
    "pyyaml",
]

[tool.setuptools.packages.find]
exclude = ["docs"]
